import { Advertisement } from './../advertisement'

export const ADVERTISEMENT: Advertisement[] = [
  {
    landlordId: 1234,
    propertyId: 7410,
    imagePath: ['img/url1', 'img/url2'],
    rooms: 2,
    beds: 2,
    numberOfToilet: 1,
    city: 'Palermo',
    description: 'Little house close to the downcentre',
    facilities: {
      tv: true,
      wifi: true,
      breakfastIncluded: false,
      parking: false,
      kitchen: true,
      shower: true,
      bath: true,
    },
    reviews: [
      {
        title: 'Fantastic vacation',
        name: 'Mario Rossi',
        description: 'Fantastic vacation. Perfect house',
      },
      {
        title: 'Good',
        name: 'Bob Tenant',
        description: 'Nice house, very very clean',
      },
    ],
    vote: 4.5,
  },
  {
    landlordId: 4567,
    propertyId: 8520,
    imagePath: ['img/url1', 'img/url2', 'img/url3', 'img/url4'],
    rooms: 5,
    beds: 4,
    numberOfToilet: 2,
    city: 'San Vito Lo Capo',
    description: 'House not far from the sea with terrace',
    facilities: {
      tv: true,
      wifi: false,
      breakfastIncluded: false,
      parking: true,
      kitchen: true,
      shower: true,
      bath: true,
    },
    reviews: [
      {
        title: 'Good',
        name: 'Maria Tenant',
        description: 'very spacious and accessible house',
      },
    ],
    vote: 4.8,
  },
  {
    landlordId: 7890,
    propertyId: 9631,
    imagePath: ['img/url1', 'img/url2'],
    rooms: 1,
    beds: 2,
    numberOfToilet: 1,
    city: 'Rome',
    description: 'Hostel for student in the downcentre',
    facilities: {
      tv: false,
      wifi: true,
      breakfastIncluded: true,
      parking: false,
      kitchen: false,
      shower: true,
      bath: true,
    },
    reviews: [
      {
        title: 'Not great',
        name: 'Sofia Loren',
        description: 'The hostel was very very caotic',
      },
      {
        title: 'Terrible',
        name: 'Giuseppe Conte',
        description: 'very busy and people without masks',
      },
    ],
    vote: 2.6,
  },
  {
    landlordId: 3458,
    propertyId: 7613,
    imagePath: ['img/url1', 'img/url2', 'img/url3', 'img/url4'],
    rooms: 2,
    beds: 3,
    numberOfToilet: 1,
    city: 'Milan',
    description: 'Little house for students',
    facilities: {
      tv: true,
      wifi: true,
      breakfastIncluded: false,
      parking: true,
      kitchen: true,
      shower: true,
      bath: true,
    },
    reviews: [
      {
        title: 'Fantastic',
        name: 'Marie Yellow',
        description: 'Very spacious and clean house',
      },
      {
        title: 'Perfect',
        name: 'Richard Green',
        description: 'Very friendly people',
      },
      {
        title: 'Superb',
        name: 'Giulie Brown',
        description: 'Very modern house',
      },
    ],
    vote: 5.0,
  },
]
